homework done
NotUrBruddah/final-project-10th-sprint pull request #1
Opened 2024-08-29 21:56 UTC by NotUrBruddah

2024-08-29 22:12 UTC, dirtymew requested changes
Привет Андрей

хорошая работа - одну ошибку нужно исправить

2024-08-29 22:12 UTC, dirtymew commented on task.sh
> +cp -r -T dir2 dir3/dir4
-T есть не во всех версиях cp

2024-08-29 22:12 UTC, dirtymew commented on task.sh
> +NAME='Всем студентам'
тут ошибка - нужно  переменную окружения создать а не просто переменную

2024-08-30 06:13 UTC, NotUrBruddah commented on task.sh
> +cp -r -T dir2 dir3/dir4
исправил на /.

2024-08-30 06:14 UTC, NotUrBruddah commented on task.sh
> +NAME='Всем студентам'
да, нужен export, поправил

2024-08-30 08:09 UTC, dirtymew approved these changes
Андрей

все отлично - зачет

2024-12-04 08:38 UTC, merged